services:
  # Aplicación FastAPI + StudNova IA
  web:
    build:
      context: ..
      dockerfile: dockerizar/Dockerfile
    container_name: studnova_app
    restart: always
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@host.docker.internal:5432/studnova
    env_file:
      - ../.env
    volumes:
      - ../app:/app/app
      - ../ia:/app/ia
      - ../principal:/app/principal
      - ../login:/app/login
      - ../principal interfaz:/app/principal interfaz
      - ../base_datos.py:/app/base_datos.py
      - ../principal.py:/app/principal.py
